#!/bin/bash

ARGS="$ARGS -bios ./RELEASEX64_OVMF.fd"
ARGS="$ARGS -append "video=efifb:1280x720""

sudo /usr/bin/qemu-system-x86_64 \
	-cpu  max \
     -m 1024m \
     -machine q35  \
     -object rng-random,filename=/dev/urandom,id=rng0 \
     -device virtio-rng-pci,rng=rng0 \
     -device e1000,netdev=n1 \
     -netdev user,id=n1,hostfwd=tcp:127.0.0.1:23-:23,net=192.168.1.0/24,host=192.168.1.1 \
     -serial /dev/tty  \
     -monitor /dev/null  \
     $ARGS \
     $*

     reset
     exit 0

# add the following line to qemu if you want to snoop packets.
	-object filter-dump,id=f1,netdev=n1,file=/tmp/vm0.pcap \
