#!/bin/bash

sudo qemu-system-riscv64 \
  -machine virt \
  -object rng-random,filename=/dev/urandom,id=rng0 \
  -device virtio-rng-pci,rng=rng0 \
  -device virtio-net-device,netdev=n0 \
  -netdev user,id=n0,hostfwd=tcp:127.0.0.1:42-:23,net=192.168.2.0/24,host=192.168.2.1 \
  -serial /dev/tty  \
  -monitor /dev/null \
  $ARGS $*

reset
exit 0
